### PR TITLE
Navigation update

### PR DESCRIPTION
**Pull request by preciousakams**
### Commit details

- added logo
- updated sidebar styling

### CODE REVIEW

**Review by ahzamir — CHANGES_REQUESTED** [review]
## Hi @kamzzy    😃, 👋

### Status:  Changes Required ⚠️
You are almost there, a few changes are required to finish the task. Please check the comments below.

AlonzoLeroneThisCloseGIF

### Highlights

The branch looks professional ✔️
You have a descriptive PR ✔️
Nice user page design, according to the requirement ✔️
No linters issues ✔️
Great commit messages ✔️

### Optional suggestions

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@ahzamir ](https://github.com/ahzamir) in your question so I can receive the notification.

**Comment by ahzamir** [comment]
@kamzzy  user login(SignUp) page should render automatically when the user opens the project if there was no user data in the local storage.

- Make it as default page if there was no data in local storage.

**Comment by ahzamir** [comment]
@kamzzy  Please add functionality for social buttons in your navbar you can copy the onclick from the `Rooms` component.

**Comment by ahzamir** [comment]
- Make sure your design is aligned with the requirements.
  - As you can see the required design for the navbar has a few differences with your design please make sure your design is same like given design.

Screenshot 2022-10-10 133410


Screenshot 2022-10-10 135735

**Comment by kamzzy** [comment]
@ahzamir 
I've implemented the changes to the navigation bar kindly review it again.

**Review by ahzamir — CHANGES_REQUESTED** [review]
## Hi @kamzzy    😃, 👋

### Status:  Changes Required ⚠️
Good job so far, good implementations of required changes but you still need to work on it to complete your task.
- Please check the comments below.

**Comment by ahzamir** [comment]
@kamzzy  You have implemented all required changes, Thanks for that but your design is not responsive. Please make sure your design is responsive for both mobile and desktop versions as required in the project descriptions.
  - Please check the design for the mobile version.
    - The navbar links and social icons.

Screenshot 2022-10-11 015329

**Comment by ahzamir** [comment]
@kamzzy 
- And when you worked on the navbar for responsive, don't forget to add hover to your login page submit button.
  - You can check the `Add Room` and `Delete Room` pages buttons on hover. Your button should be the same on hover.

Screenshot 2022-10-11 020628

**Review by ahzamir — APPROVED** [review]
## Hi @kamzzy    😃, 👋

### Status:  Approved 🎉✅👍
Good job so far, it is time to merge your branch.

### Highlights


Well-implementation of the required changes. ✔️
No linters issues ✔️
Great commit messages ✔️

### Optional suggestions

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me [@ahzamir ](https://github.com/ahzamir) in your question so I can receive the notification.

**Pull request merged**
