### PR TITLE
Design fix improvements

### PR DESCRIPTION
**Pull request by ahzamir**
### In this pull request, I solved some design issues for the mobile version and added the loading spinner for pages:

- I solved the design issues for the `Delete Room`, `My Reservations`, and `Make Reservation` pages for the mobile version.
- I solved the no-user rule issue for the `Make Reservation` page.
- I added the loading spinner for the following pages while loading(fetching) data from API:
  - `Rooms`
  - `Room`
  - `Delete Room`

### CODE REVIEW

**Comment by ahzamir** [comment]
@huseyinbiyik  @kamzzy  @felixodette 
Please review my pull request I have solved some issues on the project and made some improvements. 👍😊✅

**Comment by huseyinbiyik** [comment]
Hey @ahzamir,
All look fine from my side. Thank you for the contribution 👍

**Review by kamzzy — APPROVED** [review]
# Approved 👏  

### @ahzamir 

### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 

- The branch looks professional ✔️
- You have a descriptive PR ✔️
- No linters issues ✔️
- Great commit messages ✔️

There is nothing else to say other than... it's time to merge it :shipit: 
### **Congratulations!** 🎉 
image



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Comment by ahzamir** [comment]
@huseyinbiyik @kamzzy  Thank you very much for your kind review and feedback. 👍😊✅

**Pull request merged**
