### PR TITLE
Add Room component styling

### PR DESCRIPTION
**Pull request by huseyinbiyik**
Hello! 🖖
You can find the features added for this Pull Request below. 🧩

- Add styling to the Add Room form page for mobile and desktop
- Fix nav footer overlay issue

Thank you for your review in advance! 🤓

### CODE REVIEW

**Review by ahzamir — COMMENTED** [review]
## Hi @huseyinbiyik    😃, 👋

### Status: Approved 🎉👍

QualityGIF

### Highlights

The branch looks professional ✔️
You have a descriptive PR ✔️
The design looks nice and is according to the given design ✔️
No linters issues ✔️
Great commit messages ✔️

### Optional suggestions

- Please check the comment below:
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@ahzamir ](https://github.com/ahzamir) in your question so I can receive the notification.

**Comment by huseyinbiyik** [comment]
Thank you for your review @ahzamir. It doesn't look so good and I am aware of it but we can improve it later for sure.

**Comment by ahzamir** [comment]
@huseyinbiyik 
[OPTIONAL]
- Please add a hover to your `Submit` button.
- Please add focus or active to your form inputs to be in white background-color and the color black

**Comment by ahzamir** [comment]
@huseyinbiyik 
[OPTIONAL] 

- For the mobile version of the form inputs to be a little smaller it would look nice.
- For the submit button give it the `fw-bold` to make its text bold.

These optional changes are not required but if you had time after finishing the main requirements you can work on them so it would look better.

Happy coding.

**Pull request merged**
