### PR TITLE
Styling for room

### PR DESCRIPTION
**Pull request by kamzzy**
### Commit details

added styling for the room page

### CODE REVIEW

**Comment by huseyinbiyik** [comment]
## Required Changes ♻️
## Hi @kamzzy , 
 ### You have been doing a tremendous job so far :ok_hand:

## To Improve 🙏
- [ ] Kindly check the overflow on the desktop page view like below.
- [ ] 
Screen Recording 2022-10-10 at 3 26 50 PM

- [ ] Room description white does not match the design provided.
Screen Shot 2022-10-10 at 3 35 57 PM

- [ ] Back button has no action. Kindly check the button action, it can go to the last page.
- [ ] Reserve button does not match the design provided. You can use the button design on the new user form.

- Please check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
#### Please remember to tag me in your question so I can receive the notification.
**_Note: Please do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Review by huseyinbiyik — CHANGES_REQUESTED** [review]
## Required Changes ♻️
## Hi @kamzzy , 
 ### You have been doing a tremendous job so far :ok_hand:

## To Improve 🙏
- [ ] Kindly check the overflow on the desktop page view like below.

Screen Recording 2022-10-10 at 3 26 50 PM

- [ ] Room description white does not match the design provided.
Screen Shot 2022-10-10 at 3 35 57 PM

- [ ] Back button has no action. Kindly check the button action, it can go to the last page.
- [ ] Reserve button does not match the design provided. You can use the button design on the new user form.

- Please check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
#### Please remember to tag me in your question so I can receive the notification.

**Comment by kamzzy** [comment]
@huseyinbiyik 
I've implemented the changes as discussed, kindly go through and give me your feedback

**Review by huseyinbiyik — APPROVED** [review]
Hi @kamzzy , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 💯 
- No linters errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 



## Optional suggestions:


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**Pull request merged**
